{
    'name': "LSV Common features (project)",
    'version': "3.0-dev20",
    'summary': "",
    'depends': ['project','contacts'],
    'data': {
        'security/module_groups.xml',
        'data/addendum_description_data.xml',
        'data/endorsement_reason_data.xml',
        'data/policy_type_data.xml',
        'data/resident_role_data.xml',
        'security/ir.model.access.csv',
        'views/addendum_description_views.xml',
        'views/policy_type_views.xml',
        'views/resident_role_views.xml',
        'views/endorsement_reason_views.xml',
        'views/module_menuitems.xml',
        'views/rest_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/addendum_views.xml',
        'views/policy_views.xml',
        'views/bail_views.xml',
        'views/planning_views.xml',
        'views/subproject_views.xml',
        'views/project_project_views.xml',
    },
    'installable': True,
    'auto_install': False,
    'license': "LGPL-3",
}
